// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAB86v4QWCXdjP6ffElmu79nRlZKO_8nc',
    appId: '1:528203664172:web:581762d9d00bcedc10fa89',
    messagingSenderId: '528203664172',
    projectId: 'task-master-f202e',
    authDomain: 'task-master-f202e.firebaseapp.com',
    storageBucket: 'task-master-f202e.appspot.com',
    measurementId: 'G-BRPXET95KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTd6OVtEelOTG_aUUORqrSbtCN7ScGzzo',
    appId: '1:528203664172:android:ea2099fd794708f310fa89',
    messagingSenderId: '528203664172',
    projectId: 'task-master-f202e',
    storageBucket: 'task-master-f202e.appspot.com',
  );
}
